const themes = [
  { theme: 'HEART' },
  {
    theme: 'CAT',
  },
  {
    theme: 'PIZZA',
  },
  {
    theme: 'SNAKE',
  },
  {
    theme: 'RAINBOW',
  },
  {
    theme: 'STRAWBERRY',
  },
  {
    theme: 'SKULL',
  },
  {
    theme: 'POTION',
  },
  {
    theme: 'VAMPIRE',
  },
  {
    theme: 'SWORD',
  },
  {
    theme: 'MOON',
  },
  {
    theme: 'GHOST',
  },
  {
    theme: 'MONEY',
  },
  {
    theme: 'BUNNY',
  },
  {
    theme: 'ROSE',
  },
  {
    theme: 'ALIEN',
  },
  {
    theme: 'MUSHROOM',
  },
  {
    theme: 'SMILE',
  },
  {
    theme: 'DOG',
  },
];

let grid = [
  { id: 0, minigrid: '#FFFFFF' },
  { id: 1, minigrid: '#FFFFFF' },
  { id: 2, minigrid: '#FFFFFF' },
  { id: 3, minigrid: '#FFFFFF' },
  { id: 4, minigrid: '#FFFFFF' },
  { id: 5, minigrid: '#FFFFFF' },
  { id: 6, minigrid: '#FFFFFF' },
  { id: 7, minigrid: '#FFFFFF' },
  { id: 8, minigrid: '#FFFFFF' },
  { id: 9, minigrid: '#FFFFFF' },
  { id: 10, minigrid: '#FFFFFF' },
  { id: 11, minigrid: '#FFFFFF' },
  { id: 12, minigrid: '#FFFFFF' },
  { id: 13, minigrid: '#FFFFFF' },
  { id: 14, minigrid: '#FFFFFF' },
  { id: 15, minigrid: '#FFFFFF' },
  { id: 16, minigrid: '#FFFFFF' },
  { id: 17, minigrid: '#FFFFFF' },
  { id: 18, minigrid: '#FFFFFF' },
  { id: 19, minigrid: '#FFFFFF' },
  { id: 20, minigrid: '#FFFFFF' },
  { id: 21, minigrid: '#FFFFFF' },
  { id: 22, minigrid: '#FFFFFF' },
  { id: 23, minigrid: '#FFFFFF' },
  { id: 24, minigrid: '#FFFFFF' },
  { id: 25, minigrid: '#FFFFFF' },
  { id: 26, minigrid: '#FFFFFF' },
  { id: 27, minigrid: '#FFFFFF' },
  { id: 28, minigrid: '#FFFFFF' },
  { id: 29, minigrid: '#FFFFFF' },
  { id: 30, minigrid: '#FFFFFF' },
  { id: 31, minigrid: '#FFFFFF' },
  { id: 32, minigrid: '#FFFFFF' },
  { id: 33, minigrid: '#FFFFFF' },
  { id: 34, minigrid: '#FFFFFF' },
  { id: 35, minigrid: '#FFFFFF' },
  { id: 36, minigrid: '#FFFFFF' },
  { id: 37, minigrid: '#FFFFFF' },
  { id: 38, minigrid: '#FFFFFF' },
  { id: 39, minigrid: '#FFFFFF' },
  { id: 40, minigrid: '#FFFFFF' },
  { id: 41, minigrid: '#FFFFFF' },
  { id: 42, minigrid: '#FFFFFF' },
  { id: 43, minigrid: '#FFFFFF' },
  { id: 44, minigrid: '#FFFFFF' },
  { id: 45, minigrid: '#FFFFFF' },
  { id: 46, minigrid: '#FFFFFF' },
  { id: 47, minigrid: '#FFFFFF' },
  { id: 48, minigrid: '#FFFFFF' },
  { id: 49, minigrid: '#FFFFFF' },
  { id: 50, minigrid: '#FFFFFF' },
  { id: 51, minigrid: '#FFFFFF' },
  { id: 52, minigrid: '#FFFFFF' },
  { id: 53, minigrid: '#FFFFFF' },
  { id: 54, minigrid: '#FFFFFF' },
  { id: 55, minigrid: '#FFFFFF' },
  { id: 56, minigrid: '#FFFFFF' },
  { id: 57, minigrid: '#FFFFFF' },
  { id: 58, minigrid: '#FFFFFF' },
  { id: 59, minigrid: '#FFFFFF' },
  { id: 60, minigrid: '#FFFFFF' },
  { id: 61, minigrid: '#FFFFFF' },
  { id: 62, minigrid: '#FFFFFF' },
  { id: 63, minigrid: '#FFFFFF' },
  { id: 64, minigrid: '#FFFFFF' },
  { id: 65, minigrid: '#FFFFFF' },
  { id: 66, minigrid: '#FFFFFF' },
  { id: 67, minigrid: '#FFFFFF' },
  { id: 68, minigrid: '#FFFFFF' },
  { id: 69, minigrid: '#FFFFFF' },
  { id: 70, minigrid: '#FFFFFF' },
  { id: 71, minigrid: '#FFFFFF' },
  { id: 72, minigrid: '#FFFFFF' },
  { id: 73, minigrid: '#FFFFFF' },
  { id: 74, minigrid: '#FFFFFF' },
  { id: 75, minigrid: '#FFFFFF' },
  { id: 76, minigrid: '#FFFFFF' },
  { id: 77, minigrid: '#FFFFFF' },
  { id: 78, minigrid: '#FFFFFF' },
  { id: 79, minigrid: '#FFFFFF' },
  { id: 80, minigrid: '#FFFFFF' },
  { id: 81, minigrid: '#FFFFFF' },
  { id: 82, minigrid: '#FFFFFF' },
  { id: 83, minigrid: '#FFFFFF' },
  { id: 84, minigrid: '#FFFFFF' },
  { id: 85, minigrid: '#FFFFFF' },
  { id: 86, minigrid: '#FFFFFF' },
  { id: 87, minigrid: '#FFFFFF' },
  { id: 88, minigrid: '#FFFFFF' },
  { id: 89, minigrid: '#FFFFFF' },
  { id: 90, minigrid: '#FFFFFF' },
  { id: 91, minigrid: '#FFFFFF' },
  { id: 92, minigrid: '#FFFFFF' },
  { id: 93, minigrid: '#FFFFFF' },
  { id: 94, minigrid: '#FFFFFF' },
  { id: 95, minigrid: '#FFFFFF' },
  { id: 96, minigrid: '#FFFFFF' },
  { id: 97, minigrid: '#FFFFFF' },
  { id: 98, minigrid: '#FFFFFF' },
  { id: 99, minigrid: '#FFFFFF' },
];
const palette = [
  { color: '#E6E7E7' },
  { color: '#31373D' },
  { color: '#C1694F' },
  { color: '#55B1ED' },
  { color: '#78B159' },
  { color: '#A98ED6' },
  { color: '#DE2E44' },
  { color: '#FACB58' },
  { color: '#FFFFFF' },
];
export default { themes, grid, palette };
